### ISSUE TITLE
TFT70 Vertical GUI

### ISSUE THREAD

**Issue by Akds4877** [bigtreetech/BTT-TFT35-E3-V3.0#82]
Hey, i want to place my TFT on vertical point and there is no space in my Printer body for horizontal, so i did the configuration in portrait mode but it does not look well as the orientation is not so cool so please help me to make my TFT70 on Vertical Mode.
![IMG_20220527_161846909](https://user-images.githubusercontent.com/105791259/170927199-99cdc6d0-07ad-4295-b727-1c91eb7d5422.jpg)

**Comment by radek8** [comment]
The vertical mode is still under development and is not fine-tuned.
Icons and Appearance is primarily designed for horizontal mode. Because the same icons are used, vertical mode will not be as perfect as horizontal. Nevertheless, the programmers try to adapt it as best they can.
This storage, however, unfortunately monitors few users.
It will be better if you publish your problem here.

https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware/issues

Maybe someone will react to it.

**Comment by Akds4877** [comment]
Okay 

Thank you
